export const recipes = [
  {
    id: 1,
    title: "Spaghetti Carbonara",
    image:
      "https://media.istockphoto.com/id/1344241923/vi/anh/spaghetti-v%E1%BB%9Bi-th%E1%BB%8Bt-vi%C3%AAn-v%C3%A0-s%E1%BB%91t-c%C3%A0-chua-m%C3%AC-%E1%BB%91ng-%C3%BD.jpg?s=612x612&w=0&k=20&c=gEgei4SCpsPDlbVvmL8o1UnVoOrUw0jXH8TDhpeH4gM=",
    description: "Món Ý truyền thống với sốt kem trứng và thịt xông khói.",
    rating: 4.8,
    prepTime: "15 phút",
    cookTime: "20 phút",
    difficulty: "Trung bình",
    author: "Chef Mario",
  },
  {
    id: 2,
    title: "Bánh Mì Việt Nam",
    image:
      "https://banhmi.mein.vn/wp-content/uploads/2023/12/Banh-mi-Me-In-1.jpg",
    description: "Bánh mì giòn rụm, nhân thịt và rau thơm.",
    rating: 4.9,
    prepTime: "10 phút",
    cookTime: "15 phút",
    difficulty: "Dễ",
    author: "Chef Linh",
  },
  {
    id: 3,
    title: "Phở Bò Hà Nội",
    image:
      "https://cdn.tgdd.vn/Files/2022/01/25/1412805/cach-nau-pho-bo-nam-dinh-chuan-vi-thom-ngon-nhu-hang-quan-202201250230038502.jpg",
    description: "Món phở truyền thống với nước dùng ngọt thơm và thịt bò mềm.",
    rating: 4.9,
    prepTime: "30 phút",
    cookTime: "3 giờ",
    difficulty: "Khó",
    author: "Chef Hùng",
  },
  {
    id: 4,
    title: "Gỏi Cuốn Tôm Thịt",
    image:
      "https://i.ytimg.com/vi/w34Qnc-9KBU/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAzXE6ASDMpVme1qsjbkQx4v-KaYA",
    description: "Cuốn rau mát với tôm tươi, thịt heo và bún.",
    rating: 4.5,
    prepTime: "20 phút",
    cookTime: "15 phút",
    difficulty: "Dễ",
    author: "Chef Trang",
  },
  {
    id: 5,
    title: "Cơm Tấm Sườn Bì Chả",
    image:
      "https://i-giadinh.vnecdn.net/2024/03/07/7Honthinthnhphm1-1709800144-8583-1709800424.jpg",
    description: "Cơm với sườn nướng, bì heo và trứng chiên.",
    rating: 4.7,
    prepTime: "15 phút",
    cookTime: "30 phút",
    difficulty: "Trung bình",
    author: "Chef Minh",
  },
  {
    id: 6,
    title: "Bún Chả Hà Nội",
    image:
      "https://khaihoanphuquoc.com.vn/wp-content/uploads/2023/08/cach-lam-nuoc-mam-bun-cha-02.jpg",
    description: "Bún ăn kèm với thịt viên nướng và nước mắm pha.",
    rating: 4.8,
    prepTime: "25 phút",
    cookTime: "20 phút",
    difficulty: "Trung bình",
    author: "Chef Thu",
  },
  {
    id: 7,
    title: "Cá Kho Tộ",
    image: "https://i.ytimg.com/vi/zvlct2ZXhj8/sddefault.jpg",
    description: "Cá kho với nước mắm và tiêu trong nồi đất.",
    rating: 4.6,
    prepTime: "10 phút",
    cookTime: "40 phút",
    difficulty: "Trung bình",
    author: "Chef Quang",
  },
  {
    id: 8,
    title: "Bún Bò Huế",
    image: "https://i.ytimg.com/vi/A_o2qfaTgKs/maxresdefault.jpg",
    description: "Bún với thịt bò, giò heo và nước dùng cay nồng.",
    rating: 4.9,
    prepTime: "30 phút",
    cookTime: "2 giờ",
    difficulty: "Khó",
    author: "Chef Huế",
  },
  {
    id: 9,
    title: "Bánh Xèo",
    image:
      "https://daylambanh.edu.vn/wp-content/uploads/2019/03/banh-xeo-bang-bot-pha-san-600x400.jpg",
    description: "Bánh giòn với nhân tôm, thịt, giá đỗ và ăn kèm rau sống.",
    rating: 4.7,
    prepTime: "20 phút",
    cookTime: "15 phút",
    difficulty: "Trung bình",
    author: "Chef Lan",
  },
  {
    id: 10,
    title: "Gà Nướng Muối Ớt",
    image:
      "https://beptruong.edu.vn/wp-content/uploads/2021/03/ga-nuong-muoi-ot.jpg",
    description: "Gà nướng ướp muối ớt thơm nồng.",
    rating: 4.6,
    prepTime: "15 phút",
    cookTime: "45 phút",
    difficulty: "Trung bình",
    author: "Chef Dũng",
  },
  {
    id: 11,
    title: "Canh Chua Cá Lóc",
    image:
      "https://i-giadinh.vnecdn.net/2023/04/25/Thanh-pham-1-1-7239-1682395675.jpg",
    description: "Canh chua ngọt với cá lóc, đậu bắp, dứa và rau thơm.",
    rating: 4.5,
    prepTime: "20 phút",
    cookTime: "25 phút",
    difficulty: "Dễ",
    author: "Chef Mai",
  },
  {
    id: 12,
    title: "Bò Lúc Lắc",
    image:
      "https://hidafoods.vn/wp-content/uploads/2023/07/cach-lam-bo-luc-lac-thom-ngon-chuan-vi-nha-hang-1.jpg",
    description: "Thịt bò xào với hành tây, ớt chuông và xốt đậm đà.",
    rating: 4.7,
    prepTime: "15 phút",
    cookTime: "10 phút",
    difficulty: "Dễ",
    author: "Chef Tuấn",
  },
];
